windows_bin:
  stage: deploy
  image:
    name: sparra/pyinstaller-windows:latest
    entrypoint: ['']
  script:
    - echo "Creating Windows artifact"
    - pip install -r ./test/requirements.txt
    - cd ./test && pyinstaller --onefile main.py
    - cp ./dist/*.exe ../
  rules:
    - when: always
  artifacts:
    paths:
      - '*.exe'
    when: always
    expire_in: 2 week

linux_bin:
  stage: deploy
  image:
    name: sparra/pyinstaller-linux:latest
    entrypoint: ['']
  script:
    - echo "Creating Linux artifact"
    - pip install -r ./test/requirements.txt
    - cd ./test && pyinstaller --onefile main.py
  rules:
    - when: always
  artifacts:
    paths:
      - ./test/dist/*
    when: always
    expire_in: 2 week

linux_slim_bin:
  stage: deploy
  image:
    name: sparra/pyinstaller-linux:latest-slim
    entrypoint: ['']
  script:
    - echo "Creating Linux artifact"
    - pip install -r ./test/requirements.txt
    - cd ./test && pyinstaller --onefile main.py
  rules:
    - when: always
  artifacts:
    paths:
      - ./test/dist/*
    when: always
    expire_in: 2 week
