FROM ubuntu:22.04
SHELL ["/bin/bash", "-i", "-c"]

LABEL maintainer="f.batonogov@yandex.ru"

ARG PYTHON_VERSION=3.11.1
ARG PYINSTALLER_VERSION=5.7.0

ENV PYPI_URL=https://pypi.python.org/
ENV PYPI_INDEX_URL=https://pypi.python.org/simple

RUN \
    set -x \
    # update system
    && apt-get update \
    # install requirements
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        wget \
        git \
        libbz2-dev \
        libreadline-dev \
        libsqlite3-dev \
        libssl-dev \
        zlib1g-dev \
        libffi-dev \
        # optional libraries
        libgdbm-dev \
        libgdbm6 \
        uuid-dev \
        # upx
        upx \
        # lzma & xz-utils
        liblzma-dev \
        xz-utils

# install python
RUN mkdir python && \
    cd python && \
    wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz && \
    tar xf Python-${PYTHON_VERSION}.tar.xz && \
    rm Python-${PYTHON_VERSION}.tar.xz && \
    cd Python-${PYTHON_VERSION} && \
    ./configure --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib" && \
    make && \
    make install

# install pyinstaller
RUN pip3 install pyinstaller==$PYINSTALLER_VERSION

COPY entrypoint-linux.sh /entrypoint.sh

RUN mkdir /src/ && \
    chmod +x /entrypoint.sh

VOLUME /src/
WORKDIR /src/

ENTRYPOINT ["/entrypoint.sh"]
