# Use ARG to set the Python version
ARG PYTHON_VERSION=3.13.0
FROM python:${PYTHON_VERSION}
SHELL ["/bin/bash", "-i", "-c"]

# Define maintainer information
LABEL maintainer="f.batonogov@yandex.ru"

# Define the PyInstaller version and necessary environment variables
ARG PYINSTALLER_VERSION=6.11.0
ENV PYPI_URL=https://pypi.python.org/
ENV PYPI_INDEX_URL=https://pypi.python.org/simple
ENV PYTHONUNBUFFERED=1

# Copy the entrypoint script
COPY entrypoint-linux.sh /entrypoint.sh

# Install dependencies, PyInstaller, and set execute permissions for the entrypoint
RUN pip install --no-cache-dir pyinstaller==$PYINSTALLER_VERSION \
    && chmod +x /entrypoint.sh

# Set the working directory and mount the volume
VOLUME /src/
WORKDIR /src/

# Set the entrypoint
ENTRYPOINT ["/entrypoint.sh"]
