FROM sickcodes/docker-osx:sonoma
SHELL ["/bin/bash", "-i", "-c"]

LABEL maintainer="f.batonogov@yandex.ru"

ARG PYINSTALLER_VERSION=6.11.0

ENV PYPI_URL=https://pypi.python.org/
ENV PYPI_INDEX_URL=https://pypi.python.org/simple

COPY entrypoint-osx.sh /entrypoint.sh

USER root

RUN pacman --noconfirm -Sy python-pipx

RUN pipx ensurepath \
    && pipx install pip \
    && pipx install pyinstaller==$PYINSTALLER_VERSION \
    && chmod +x /entrypoint.sh

VOLUME /src/
WORKDIR /src/

ENTRYPOINT ["/entrypoint.sh"]
