FROM python:3.12.4-slim
SHELL ["/bin/bash", "-i", "-c"]

LABEL maintainer="f.batonogov@yandex.ru"

ARG PYINSTALLER_VERSION=6.9.0

ENV PYPI_URL=https://pypi.python.org/
ENV PYPI_INDEX_URL=https://pypi.python.org/simple

COPY entrypoint-linux.sh /entrypoint.sh

RUN apt update \
    && apt install -y \
        binutils \
        gcc \
        zlib1g-dev \
    && apt clean \
    && rm -rf \
        /var/lib/apt/lists/* \
        /var/cache/* \
    && pip3 install \
        pyinstaller==$PYINSTALLER_VERSION \
    && pip3 cache purge \
    && chmod +x /entrypoint.sh

VOLUME /src/
WORKDIR /src/

ENTRYPOINT ["/entrypoint.sh"]
