ARG PYTHON_VERSION=3.12.6
FROM python:${PYTHON_VERSION}
SHELL ["/bin/bash", "-i", "-c"]

LABEL maintainer="f.batonogov@yandex.ru"

ARG PYINSTALLER_VERSION=6.10.0

ENV PYPI_URL=https://pypi.python.org/
ENV PYPI_INDEX_URL=https://pypi.python.org/simple

COPY entrypoint-linux.sh /entrypoint.sh

RUN pip3 install --no-cache-dir \
        pyinstaller==$PYINSTALLER_VERSION \
    && chmod +x /entrypoint.sh

VOLUME /src/
WORKDIR /src/

ENTRYPOINT ["/entrypoint.sh"]
