name: AURO PR

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  pull-request:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Auto Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: main
