name: Docker Image CI Linux docker.io

on:
  push:
    tags:
      - v*.*.*
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          file: ./Dockerfile-py3-linux-slim
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v5
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          push: true
          build-args: PYTHON_VERSION=3.11.9-slim-bookworm
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-linux:${{ github.ref_name }}-slim
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-linux:${{ github.ref_name }}-slim-bookworm
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-linux:latest-slim

      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          file: ./Dockerfile-py3-linux-slim
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          push: true
          build-args: PYTHON_VERSION=3.11.9-slim-bullseye
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-linux:${{ github.ref_name }}-slim-bullseye

      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          file: ./Dockerfile-py3-linux
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v5
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          push: true
          build-args: PYTHON_VERSION=3.11.9-bookworm
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-linux:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-linux:${{ github.ref_name }}-bookworm
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-linux:latest

      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          file: ./Dockerfile-py3-linux
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          push: true
          build-args: PYTHON_VERSION=3.11.9-bullseye
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-linux:${{ github.ref_name }}-bullseye
