name: Docker Image CI Windows docker.io

on:
  push:
    tags:
      - v*.*.*
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          file: ./Dockerfile-py3-windows
          platforms: |
            linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-windows:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pyinstaller-windows:latest
